//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hepsiburada.MarsRover.GlobalResources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class ExceptionMessage {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ExceptionMessage() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Hepsiburada.MarsRover.GlobalResources.ExceptionMessage", typeof(ExceptionMessage).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success.
        /// </summary>
        public static string EX0000 {
            get {
                return ResourceManager.GetString("EX0000", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected Error!.
        /// </summary>
        public static string EX1001 {
            get {
                return ResourceManager.GetString("EX1001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It is not possible to get out of the plateau area..
        /// </summary>
        public static string EX1002 {
            get {
                return ResourceManager.GetString("EX1002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is another rover in the position..
        /// </summary>
        public static string EX1003 {
            get {
                return ResourceManager.GetString("EX1003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Technical error has occurred!.
        /// </summary>
        public static string EX1004 {
            get {
                return ResourceManager.GetString("EX1004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A parameter error occurred while parsing the input values!.
        /// </summary>
        public static string EX1005 {
            get {
                return ResourceManager.GetString("EX1005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input values could not be parsed!.
        /// </summary>
        public static string EX1006 {
            get {
                return ResourceManager.GetString("EX1006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected direction command!.
        /// </summary>
        public static string EX1007 {
            get {
                return ResourceManager.GetString("EX1007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected direction command!.
        /// </summary>
        public static string EX1008 {
            get {
                return ResourceManager.GetString("EX1008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected direction command!.
        /// </summary>
        public static string EX1009 {
            get {
                return ResourceManager.GetString("EX1009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unexpected direction command!.
        /// </summary>
        public static string EX1010 {
            get {
                return ResourceManager.GetString("EX1010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rover position is not in the expected format!.
        /// </summary>
        public static string EX1011 {
            get {
                return ResourceManager.GetString("EX1011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Plateau area is not in the expected format!.
        /// </summary>
        public static string EX1012 {
            get {
                return ResourceManager.GetString("EX1012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input values cannot be empty!.
        /// </summary>
        public static string EX1013 {
            get {
                return ResourceManager.GetString("EX1013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid rover position on the plateau!.
        /// </summary>
        public static string EX1014 {
            get {
                return ResourceManager.GetString("EX1014", resourceCulture);
            }
        }
    }
}
